#POST http://localhost:8080/breeds/cat/add
#Content-Type: application/json
#
#{
#  "breedName": "Koteczek"
#}
###
#PUT http://localhost:8080/breeds/dog/update/Labrador/a b c d e f g

###
#DELETE http://localhost:8080/breeds/dog/delete/a b c d e f g