#POST http://localhost:8080/comments/add
#Content-Type: application/json
#
#{
#  "content": "Test2",
#  "date": "2024-06-08"
#}


#PUT http://localhost:8080/comments/update/2
#Content-Type: application/json
#
#{
#  "content": "updated bitch",
#  "date": "2024-06-08"
#}


#POST http://localhost:8080/comments/animals/add/2
#Content-Type: application/json
#
#{
#  "content": "Test2",
#  "date": "2024-06-08"
#}


DELETE http://localhost:8080/comments/animals/delete/7/1