services:
  pet_oasis_backend:
    container_name: pet_oasis_backend
    image: pet_oasis_backend:1.0.0
    build: .
    ports:
      - 18080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://pet_oasis_database:5432/petoasis
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=password
    depends_on:
      - pet_oasis_database

  pet_oasis_database:
    container_name: pet_oasis_database
    image: postgres:12
    ports:
      - 15432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: petoasis
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}