POST http://localhost:8080/shelter/add
Content-Type: application/json

{
  "generalSystemUser": {
    "login": "shelterek21222",
    "password": "szelter",
    "isVerified": false,
    "phoneNumber": "535165760"
  },
  "shelter": {
    "name": "Szelterpsuww22123",
    "address": "guwniana",
    "website": "www.com",
    "email": "szelter@wp.pl"
  }
}
