POST http://localhost:8080/status/availability/add
Content-Type: application/json

{
  "availability": "Testing4"
}


###

#DELETE http://localhost:8080/status/availability/delete/Testing


#PUT http://localhost:8080/status/availability/update/Testgowna/Testgowna2222
