POST http://localhost:8080/badge/add
Content-Type: application/json

{
  "badgeName": "Smiechowy"
}
###
#DELETE http://localhost:8080/badge/delete/Smiechowy

#POST http://localhost:8080/badge/assign/1/Smieszny

#PUT http://localhost:8080/badge/update/Smieszny/Smiechowy