POST http://localhost:8080/cats/add
Content-Type: application/json

{
  "animal": {
    "name": "bbbb",
    "weight": 2.22,
    "height": 1.22,
    "length": 12.21,
    "description": "evil boy",
    "gender": "M",
    "enjoysPetting": true,
    "healthStatus": {
      "healthId": 1
    },
    "availabilityStatus": {
      "availabilityId": 1
    }
  },
  "cat": {
    "isDeclawed": false,
    "vocalizationLevel": 28,
    "catBreed": {
      "breedId": 1
    }
  }
}

###

# DELETE http://localhost:8080/cats/delete/1


#PUT http://localhost:8080/cats/update/1
#Content-Type: application/json
#
#{
#  "animal": {
#    "name": "Bartek"
#  }
#}