POST http://localhost:8080/person/add
Content-Type: application/json

{
  "generalSystemUser": {
    "login": "Wiktorekkkk2",
    "password": "Wiktorek",
    "isVerified": false,
    "phoneNumber": "535165760"
  },
  "person": {
    "name": "Wiktorname",
    "surname": "Kuberasurname",
    "birthDate": "2000-04-30",
    "email": "Wiktorkuberax@gmail.com",
    "gender": "M"
  }
}

###
#DELETE http://localhost:8080/person/delete/Wiktor


#PUT http://localhost:8080/person/update/Marcing
#Content-Type: application/json
#
#{
#  "login": "Marcing",
#  "password": "lmao"
#}