CREATE TABLE animal
(
    animal_id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name            VARCHAR(48)                             NOT NULL,
    birth_date      date,
    weight          FLOAT                                   NOT NULL,
    height          FLOAT                                   NOT NULL,
    length          FLOAT                                   NOT NULL,
    age             SMALLINT,
    is_neutered     BOOLEAN,
    description     VARCHAR(1024)                           NOT NULL,
    gender          VARCHAR(1)                              NOT NULL,
    enjoys_petting  BOOLEAN                                 NOT NULL,
    rating          FLOAT,
    pictureurl      VARCHAR(128),
    health_id       INTEGER,
    availability_id INTEGER,
    type            VARCHAR(255),
    parent_id       BIGINT,
    shelter_id      BIGINT,
    CONSTRAINT pk_animal PRIMARY KEY (animal_id)
);

CREATE TABLE animal_badge
(
    animal_id BIGINT  NOT NULL,
    badge_id  INTEGER NOT NULL,
    CONSTRAINT pk_animalbadge PRIMARY KEY (animal_id, badge_id)
);

CREATE TABLE animal_comment
(
    animal_id  BIGINT NOT NULL,
    comment_id BIGINT NOT NULL,
    CONSTRAINT pk_animalcomment PRIMARY KEY (animal_id, comment_id)
);

CREATE TABLE availability_status
(
    availability_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    availability    VARCHAR(64)                              NOT NULL,
    CONSTRAINT pk_availabilitystatus PRIMARY KEY (availability_id)
);

CREATE TABLE badge
(
    badge_id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    badge_name VARCHAR(48),
    CONSTRAINT pk_badge PRIMARY KEY (badge_id)
);

CREATE TABLE cat
(
    cat_id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    animal_id          BIGINT,
    is_declawed        BOOLEAN                                 NOT NULL,
    vocalization_level SMALLINT                                NOT NULL,
    favorite_treat     VARCHAR(48),
    breed_id           INTEGER,
    CONSTRAINT pk_cat PRIMARY KEY (cat_id)
);

CREATE TABLE cat_breed
(
    breed_id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    breed_name VARCHAR(48)                              NOT NULL,
    CONSTRAINT pk_catbreed PRIMARY KEY (breed_id)
);

CREATE TABLE comment
(
    comment_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    person_id  BIGINT,
    content    VARCHAR(1024)                           NOT NULL,
    date       date,
    CONSTRAINT pk_comment PRIMARY KEY (comment_id)
);

CREATE TABLE dog
(
    dog_id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    animal_id          BIGINT,
    is_muzzle_required BOOLEAN                                 NOT NULL,
    barking_level      SMALLINT                                NOT NULL,
    favorite_toy       VARCHAR(48),
    breed_id           INTEGER,
    CONSTRAINT pk_dog PRIMARY KEY (dog_id)
);

CREATE TABLE dog_breed
(
    breed_id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    breed_name VARCHAR(48)                              NOT NULL,
    CONSTRAINT pk_dogbreed PRIMARY KEY (breed_id)
);

CREATE TABLE favorite_animals
(
    person_id BIGINT NOT NULL,
    animal_id BIGINT NOT NULL,
    CONSTRAINT pk_favoriteanimals PRIMARY KEY (person_id, animal_id)
);

CREATE TABLE general_system_user
(
    system_user_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    login          VARCHAR(48)                             NOT NULL,
    password       VARCHAR(128)                            NOT NULL,
    is_verified    BOOLEAN                                 NOT NULL,
    phone_number   VARCHAR(20)                             NOT NULL,
    picture_url    VARCHAR(128),
    type           VARCHAR(255),
    parent_id      BIGINT,
    CONSTRAINT pk_generalsystemuser PRIMARY KEY (system_user_id)
);

CREATE TABLE health_status
(
    health_id     INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    health_status VARCHAR(64)                              NOT NULL,
    CONSTRAINT pk_healthstatus PRIMARY KEY (health_id)
);

CREATE TABLE person
(
    person_id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    system_user_id BIGINT,
    name           VARCHAR(32)                             NOT NULL,
    surname        VARCHAR(48)                             NOT NULL,
    birth_date     date                                    NOT NULL,
    email          VARCHAR(64)                             NOT NULL,
    gender         VARCHAR(1),
    address        VARCHAR(64),
    CONSTRAINT pk_person PRIMARY KEY (person_id)
);

CREATE TABLE shelter
(
    shelter_id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    system_user_id BIGINT,
    name           VARCHAR(96)                             NOT NULL,
    address        VARCHAR(64)                             NOT NULL,
    website        VARCHAR(128),
    email          VARCHAR(64)                             NOT NULL,
    rating         FLOAT,
    CONSTRAINT pk_shelter PRIMARY KEY (shelter_id)
);

CREATE TABLE walk
(
    walk_id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    animal_id  BIGINT,
    person_id  BIGINT,
    shelter_id BIGINT,
    status_id  INTEGER,
    start_time date,
    end_time   date,
    CONSTRAINT pk_walk PRIMARY KEY (walk_id)
);

CREATE TABLE walk_status
(
    status_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    status    VARCHAR(48)                              NOT NULL,
    CONSTRAINT pk_walkstatus PRIMARY KEY (status_id)
);

ALTER TABLE availability_status
    ADD CONSTRAINT uc_availabilitystatus_availability UNIQUE (availability);

ALTER TABLE cat
    ADD CONSTRAINT uc_cat_animal UNIQUE (animal_id);

ALTER TABLE cat_breed
    ADD CONSTRAINT uc_catbreed_breed_name UNIQUE (breed_name);

ALTER TABLE dog
    ADD CONSTRAINT uc_dog_animal UNIQUE (animal_id);

ALTER TABLE dog_breed
    ADD CONSTRAINT uc_dogbreed_breed_name UNIQUE (breed_name);

ALTER TABLE general_system_user
    ADD CONSTRAINT uc_generalsystemuser_login UNIQUE (login);

ALTER TABLE health_status
    ADD CONSTRAINT uc_healthstatus_health_status UNIQUE (health_status);

ALTER TABLE person
    ADD CONSTRAINT uc_person_system_user UNIQUE (system_user_id);

ALTER TABLE shelter
    ADD CONSTRAINT uc_shelter_name UNIQUE (name);

ALTER TABLE shelter
    ADD CONSTRAINT uc_shelter_system_user UNIQUE (system_user_id);

ALTER TABLE walk_status
    ADD CONSTRAINT uc_walkstatus_status UNIQUE (status);

ALTER TABLE animal_badge
    ADD CONSTRAINT FK_ANIMALBADGE_ON_ANIMAL FOREIGN KEY (animal_id) REFERENCES animal (animal_id);

ALTER TABLE animal_badge
    ADD CONSTRAINT FK_ANIMALBADGE_ON_BADGE FOREIGN KEY (badge_id) REFERENCES badge (badge_id);

ALTER TABLE animal_comment
    ADD CONSTRAINT FK_ANIMALCOMMENT_ON_ANIMAL FOREIGN KEY (animal_id) REFERENCES animal (animal_id);

ALTER TABLE animal_comment
    ADD CONSTRAINT FK_ANIMALCOMMENT_ON_COMMENT FOREIGN KEY (comment_id) REFERENCES comment (comment_id);

ALTER TABLE animal
    ADD CONSTRAINT FK_ANIMAL_ON_AVAILABILITY FOREIGN KEY (availability_id) REFERENCES availability_status (availability_id);

ALTER TABLE animal
    ADD CONSTRAINT FK_ANIMAL_ON_HEALTH FOREIGN KEY (health_id) REFERENCES health_status (health_id);

ALTER TABLE animal
    ADD CONSTRAINT FK_ANIMAL_ON_SHELTER FOREIGN KEY (shelter_id) REFERENCES shelter (shelter_id);

ALTER TABLE cat
    ADD CONSTRAINT FK_CAT_ON_ANIMAL FOREIGN KEY (animal_id) REFERENCES animal (animal_id);

ALTER TABLE cat
    ADD CONSTRAINT FK_CAT_ON_BREED FOREIGN KEY (breed_id) REFERENCES cat_breed (breed_id);

ALTER TABLE comment
    ADD CONSTRAINT FK_COMMENT_ON_PERSON FOREIGN KEY (person_id) REFERENCES person (person_id);

ALTER TABLE dog
    ADD CONSTRAINT FK_DOG_ON_ANIMAL FOREIGN KEY (animal_id) REFERENCES animal (animal_id);

ALTER TABLE dog
    ADD CONSTRAINT FK_DOG_ON_BREED FOREIGN KEY (breed_id) REFERENCES dog_breed (breed_id);

ALTER TABLE favorite_animals
    ADD CONSTRAINT FK_FAVORITEANIMALS_ON_ANIMAL FOREIGN KEY (animal_id) REFERENCES animal (animal_id);

ALTER TABLE favorite_animals
    ADD CONSTRAINT FK_FAVORITEANIMALS_ON_PERSON FOREIGN KEY (person_id) REFERENCES person (person_id);

ALTER TABLE person
    ADD CONSTRAINT FK_PERSON_ON_SYSTEM_USER FOREIGN KEY (system_user_id) REFERENCES general_system_user (system_user_id);

ALTER TABLE shelter
    ADD CONSTRAINT FK_SHELTER_ON_SYSTEM_USER FOREIGN KEY (system_user_id) REFERENCES general_system_user (system_user_id);

ALTER TABLE walk
    ADD CONSTRAINT FK_WALK_ON_ANIMAL FOREIGN KEY (animal_id) REFERENCES animal (animal_id);

ALTER TABLE walk
    ADD CONSTRAINT FK_WALK_ON_PERSON FOREIGN KEY (person_id) REFERENCES person (person_id);

ALTER TABLE walk
    ADD CONSTRAINT FK_WALK_ON_SHELTER FOREIGN KEY (shelter_id) REFERENCES shelter (shelter_id);

ALTER TABLE walk
    ADD CONSTRAINT FK_WALK_ON_STATUS FOREIGN KEY (status_id) REFERENCES walk_status (status_id);